version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    
    assignees:
      - "dilicalflame"

    groups:
      all-dependencies:
        patterns:
          - "*"